
technologies = {
    'A': ['Angular.js', 'Apache'],
    'B': ['Backbone.js'],
    'C': ['C++', 'C#', 'Coldfusion', 'Clojure', 'Couchbase', 'Cassandra'],
    'D': ['Dart', 'D', 'Django', 'Docker'],
    'E': ['Ember.js', 'Erlang', 'Elm', 'Elixir', 'Express.js'],
    'F': ['F#', 'Flask', 'Frege', 'FoundationDB'],
    'G': ['Go', 'Grunt.js', 'Gulp.js'],
    'H': ['Haskell', 'Hadoop', 'Hapi.js', 'Hive'],
    'I': ['Io.js', 'Idris'],
    'J': ['Julia', 'Java', 'Jython', 'JRuby'],
    'K': ['Knockout.js'],
    'L': ['Linux'],
    'M': ['Marionette.js', 'MongoDB', 'MySQL', 'MariaDB'],
    'N': ['Node.js', 'Neo4J'],
    'O': ['OCaml', 'Oracle', 'Objective C'],
    'P': ['Phoenix', 'Postgres', 'Python', 'Pig'],
    'Q': {},
    'R': ['Ruby', 'R', 'Rust'],
    'S': ['Scala', 'Spring', 'Sqlite', 'SQL Server', 'Swift', 'Smalltalk', 'Spark'],
    'T': {},
    'U': ['Ubuntu'],
    'V': ['Vagrant'],
    'W': {},
    'X': {},
    'Y': ['YARN'],
    'Z': ['Zookeeper', 'Zuul'],
}

